version: '3.9'

services:
  postgres:
    image: postgres:13.2
    container_name: labo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - local-keycloak
  keycloak:
    image: jboss/keycloak:latest
    container_name: labo-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRES_DATABASE_NAME}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - local-keycloak

networks:
  local-keycloak:
